/*
[
	perk_id,
	perk_name,
 	perk_type,
  	perk_description,
   	perk_image_position: [ x , y ] (on a grid starting at the top-left at 0,0)
 ]
*/
const tcm__perkData = [
	/*victim perks*/
	[1,"attribute point","attribute","Awards an extra attribute point to add in your character loadout.",[9,11]],
	[2,"path","fork","Choose a path.",[8,11]],

	[12,"bomb squad","proficiency","You are able to dismantle a trap without the use of a bone scrap 4 times. Dismantling a trap is 40% faster.",[2,2]],
	[13,"deadbolt","proficiency","Doors you latch are 80% harder to barge through.",[3,2]],
	[14,"efficient locksmith","proficiency","When unlocking doors, there is a 40% chance the unlock tool won't be consumed.",[5,2]],
	[15,"exit strategy","proficiency","After unlocking a door, the door stays highlighted for all Victims for 120 seconds.",[6,2]],
	[16,"highly skilled","proficiency","Your Proficiency is increased by 7.",[9,2]],
	[17,"intuition","proficiency","Holding a key item (fuse/valve) highlights the location it can be used for 100 seconds.",[1,3]],
	[18,"knock knock","proficiency","After escaping your restraints, all basement exits are highlighted for 150 seconds.",[2,3]],
	[19,"lucky lockpicker","proficiency","The very first time you use an unlock tool to open a door, it has a 100% chance to not be consumed.",[3,3]],
	[20,"medical benefits","proficiency","Healing a fellow Victim also heals yourself. The amount of health received will be 100% of total healing applied to your teammate.",[4,3]],
	[21,"pick on me","proficiency","While using an unlock tool, the door or gate you are attempting to open will be highlighted for all Victims. The effect will last 90 seconds.",[5,3]],
	[22,"rescue medic","proficiency","Healing others adds 100% more health to your target, while simultaneously healing you a random amount.",[7,3]],
	[23,"saboteur","proficiency","After using a generator or fuse box the interaction cooldown is 30 seconds longer.",[8,3]],
	[24,"tool tracks","proficiency","After escaping your restraints, all unlock tools within 50 meters will be highlighted for 120 seconds at the beginning of the match.",[0,4]],
	
	[25,"clear eyes","stealth","Clears up your vision to help identify poisoned objects, traps, and locks set by The Cook. Range is 30 meters.",[1,4]],
	[26,"cover recovery","stealth","Stamina recovery increased by 120% while using hiding spots or shadows.",[2,4]],
	[27,"fuse lights","stealth","When the fuse box is turned on or off, all Family members and the fuse box are highlighted for 120 seconds.",[4,4]],
	[28,"light on your feet","stealth","Grandpa is not alerted by the noises you make during the start of the game.",[7,4]],
	[29,"meter reader","stealth","When a Family member operates a generator, both the Family member and generator are highlighted for 120 seconds.",[8,4]],
	[30,"must have been the wind","stealth","All noise generated when interacting with crawl spaces or while gathering items will be completely disregarded. Has 5 charges.",[9,4]],
	[31,"overlooked","stealth","When Grandpa's Sonar ability is active, you will remain undetected even if you are spotted. Has 4 charges.",[0,5]],
	[32,"parting gift","stealth","When another Victim escapes, all Family members are highlighted to the perk holder for 150 seconds.",[1,5]],
	[33,"rally leader","stealth","Help all Victims recover from being incapacitated more quickly. Recovery is 35% faster.",[3,5]],
	[34,"radar detector","stealth","While Grandpa's Sonar ability is activated, all Family members are highlighted for 15 seconds. Has 7 charges.",[2,5]],
	[35,"sanguine shadow","stealth","If you drop below 70% health, it can be refilled slowly by staying hidden and motionless in shadows or hiding spots. Health received is 2.5HP per second up to a maximum of 60% of your total health.",[4,5]],
	[36,"second wind","stealth","After being injured, you are able to recover 90 stamina by avoiding damage for the next 7 seconds.",[5,5]],
	[37,"sneaky pete","stealth","Your Stealth is increased by 7.",[7,5]],
	[38,"spotter","stealth","If a Family member moves within close proximity to where you are currently hiding, they will be highlighted for all Victims to see. Highlight range is 6 meters.",[8,5]],
	[39,"twinkle toes","stealth","You have a 100% chance to not trigger bone charms, while also completely avoiding chickens.",[9,5]],
	
	[40,"agitator","strength","Incapacitating Grandpa has a greater negative effect on the Family. Family bond is reduced by 2.5 levels.",[1,6]],
	[41,"bad blood","strength","Upon death, your killer's damage output is reduced by 50% for 120 seconds, and they will be highlighted on the map for 240 seconds.",[3,6]],
	[42,"been workin' out","strength","Your Strength is increased by 7.",[4,6]],
	[43,"choose fight","strength","Sneak attacks and close encounters stun Family members for 3.5 seconds longer.",[5,6]],
	[44,"dead weight","strength","When you're the last Victim alive, the Family's proximity radius is 100% smaller than it usually is.",[6,6]],
	[45,"efficient grappler","strength","You have a 33% chance to keep your bone scrap after using it in a close encounter.",[7,6]],
	[46,"fight back","strength","After surviving a close encounter, the Family member you fought has stamina regeneration reduced by 45% for 35 seconds.",[8,6]],
	[47,"fish hooks","strength","Sneak attacks decrease the Family's max stamina for a limited amount of time. Max stamina is reduced by 75% for 30 seconds.",[9,6]],
	[48,"grappler","strength","Each button tap during a close encounter is worth more towards winning the struggle. Button taps are 30% more effective.",[0,7]],
	[49,"jack in the box","strength","When leaving a hiding spot, you take 45% less damage for 20 seconds.",[1,7]],
	[50,"tae kwon door","strength","Slamming doors on Family members will stun the target for 3 seconds.",[3,7]],
	
	[51,"am i bleeding","toughness","When your health is below 80%, you are highlighted to all fellow Victims.",[5,7]],
	[52,"bounce back better","toughness","Healing items used on you are 40% more effective. Counts for being healed and healing yourself.",[7,7]],
	[53,"efficient backstabber","toughness","Sneak attacks have a chance to not consume a bone scrap. Chance is 33%.",[8,7]],
	[54,"full hearts","toughness","While below 25% health, all healing items within 25 meters are highlighted.",[9,7]],
	[55,"jump start","toughness","Stamina consumption on dashing is reduced by 50%.",[2,8]],
	[56,"no sell","toughness","Getting hit by a Family member results in 50% less damage. Has 5 charges.",[4,8]],
	[57,"stunt double","toughness","Receive less damage when jumping out of windows or climbing down wells, and get back on your feet faster after doing so. Damage received is 70% less.",[8,8]],
	[58,"tougher stuff","toughness","Your Toughness is increased by 7.",[0,9]],
	[59,"tourniquet","toughness","After consuming a health item, you don't bleed out for 60 seconds.",[1,9]],
	[60,"what doesn't kill you","toughness","After being injured by a melee attack, avoiding additional damage for 15 seconds will reward you with 100% of the health you just lost.",[2,9]],
	
	[61,"bar room hero","endurance","Your stun time is reduced by 60%.",[1,0]],
	[63,"choose flight","endurance","After running out of stamina, refill 50% stamina. Has 5 charges.",[2,0]],
	[62,"conditioned","endurance","When you completely run out of stamina, it takes 60% less time to start regenerating.",[3,0]],
	[64,"cover charge","endurance","Sprinting uses 50% less stamina for 30 seconds upon exiting a hiding spot you occupied for at least 5 seconds.",[4,0]],
	[65,"empowered","endurance","After surviving a close encounter, you regain 30 health.",[5,0]],
	[66,"extra drip","endurance","After using a health item, you will continue to receive 3HP for 12 seconds.",[6,0]],
	[67,"fight and flight","endurance","After surviving a close encounter, movement speed is increased by 12% and stamina consumption is reduced by 50% for 20 seconds.",[7,0]],
	[68,"high tolerance","endurance","Sissy's poison isn't as effective on you. Duration is 60% shorter.",[9,0]],
	[69,"jump scare","endurance","Triggering bone charms and chickens increases your sprint speed by 12% for 12 seconds.",[2,1]],
	[70,"last ditch effort","endurance","Dropping below 50% of your max health will automatically equip a bone scrap. This only occurs if you have an empty inventory slot. Has 4 charges.",[3,1]],
	[71,"lone survivor","endurance","The last Victim alive will receive 30% added to max health and stamina. This also increases the amount of time Family members will be highlighted by 45 seconds.",[4,1]],
	[72,"ran track","endurance","Your Endurance is increased by 7.",[7,1]],
	[73,"safety in numbers","endurance","While all Victims are alive and before any have escaped, you receive 20% bonus to your max health and stamina.",[8,1]],
	[74,"slippery","endurance","After navigating gaps or crawl spaces, you move 17% faster for 10 seconds.",[9,1]],
	[75,"well trained","endurance","After jumping down a well, all bone scrap and unlock tools within 25 meters are highlighted for 60 seconds.",[1,2]],

	[76,"speed search","proficiency","If a Family member is within 10 meters, 100% more progress is awarded for each button tap during the item gathering minigame.",[9,3]],
	[77,"i can make it","endurance","When under 30% health, receive 15 points toward Endurance.",[0,1]],
	[78,"forward thinking","stealth","After escaping the basement, valve handle and fuse locations are highlighted for 90 seconds.",[3,4]],
	[79,"resilient","toughness","When under 30% health, receive 15 points towards Toughness.",[7,8]],
	[80,"fast hands","proficiency","If a Family member is within 10 meters, 75% more progress is awarded for each button tap in the lockpicking minigame.",[7,2]],
	[81,"get it off me","stealth","When escaping a trap, each button tap in the minigame adds 120% more points to progress bar, and 40% less points to failure bar.",[5,4]],
	[82,"quick exit","proficiency","If a Family member is within 10 meters, crawl spaces can be opened with 1 button tap.",[6,3]],
	[83,"trace chemicals","unique", "Powder collection points within 30 meters are highlighted for you.",[1,10]],
	[84,"well marker","stealth","After being hit, wells within 50 meters are highlighted.",[0,6]],
	[85,"seeing red","stealth","Performing a sneak attack on a Family member will highlight them for all Victims for 30 seconds.",[6,5]],
	[86,"protective aura","unique","While above 80% health, Victims within 15 meters take 30% less damage.",[9,9]],
	[87,"noise pollution","unique","Virginia's powder cloud highlights Family members who enter it for 20 seconds.",[8,9]],
	[88,"hands off!","unique","Picking up powder prevents anyone else from picking up further powder (including Virginia) for 180 seconds.",[7,9]],
	[89,"first in, last out","endurance","When you're the last Victim standing, Strength and Endurance are increased by 15 points.",[8,0]],
	[90,"coagulant","unique","Virginia's powder cloud drains 50% of the blood being carried by any Family member who enters it.",[5,9]],
	[91,"bloodar","unique","Tainted blood buckets also highlight any Family member who comes near them within a range of 9 meters for the duration they are tainted.",[4,9]],
	[92,"back for blood","strength","When sneak attacking Grandpa you decrease Family bond by an extra 30% and heal for 30% health.",[2,6]],
	[93,"artful dodger","endurance","When within 20 meters of a Family member, nearby crawl spaces are highlighted and open in 1 button tap.",[0,0]],
	[94,"immunity","endurance","Walking through a poison cloud or consuming poisoned health items does not affect you. Has 7 charges.",[1,1]],
	[95,"dietician","unique","Any blood fed to Grandpa after he has been sweet-talked is 30% less effective for the next 2 feeds.",[6,9]],
	[100,"crimson cocktail","toughness","Heals 40% of max HP by consuming blood from blood buckets. Has 4 charges.",[0,10]],
	[97,"pep talk","toughness","Sweet-talking Grandpa heals you by 30% of your maximum health.",[6,8]],
	[98,"blood clot cry","toughness","Receive 30 health whenever Granda activates his Sonar ability. Has 7 charges.",[6,7]],
	[99,"talk and run","endurance","After sweet-talking Grandpa, stamina consumption is reduced by 75% for 40 seconds.",[0,2]],
	[101,"white meat","toughness","Silencing a chicken heals you for 30% health.",[3,9]],
	[96,"final girl","unique","When you are the last victim alive, increase your maximum stamina by 30%. Shards do not break.",[2,7]],
	[102,"i know engines","toughness","Getting within 50 meters of Leatherface while his chainsaw is active, applies a noise maker visual effect to Leatherface. This allows the perk holder to track Leatherface for 25 seconds.",[1,8]],
	[103,"hush or die","stealth","When under 30% health, receive 15 points towards Stealth.",[6,4]],
	[104,"do or die","proficiency","When you're the last Victim standing, proficiency and stealth is increased by 15 points.",[4,2]],
	[105,"i can do this","proficiency","When under 30% health, receive 15 points towards Proficiency.",[0,3]],
	[106,"headstart","toughness","Valves and fuses are highlighted for 150 seconds at the start of the game.",[0,8]],
	[107,"no shock","toughness","Once a tampered generator or car battery is turned off, all connected objects are highlighted for 45 seconds.",[5,8]],
	[108,"hare or meat","proficiency","If a Family member is within 10 meters, 100% more points are awarded for each button tap during the valve minigame.",[8,2]],
	[109,"lifeline","toughness","If a tampered exit is opened, the exit will be highlighted for 45 seconds longer.",[3,8]],
	[110,"wax on wax off","strength","When under 30% health, receive 15 points towards Strength.",[4,7]],
	[111,"no stopping","endurance","If the valve or basement exits are opened, or the electric cattle grid is disabled, your stamina depletion will be reduced by 30%.",[5,1]],
	[112,"out of my head","endurance","Reduce Nancy's effectiveness by applying an 90% increase in ability depletion rate, and reduce the time of any poison effect by 9 seconds.",[6,1]],
	[113,"there they are","toughness","Family members within 10 meters of a tampered object for more than 0.5 seconds are highlighted to you for 20 seconds.",[9,8]],
	[114,"dauntless","unique","Wyatt has one 50% chance per throwing knife of retrieving it by getting close to the Family member who was hit and stunned by the knife.",[4,10]],
	[115,"versatile","unique","If at least one throwing knife is in Wyatt's inventory, bone chimes can be cut down, and does not consume a knife. Cutting down bone charms is 50% faster, whether they are cut down by a throwing knife or a bone shard.",[3,10]],
	[116,"awareness","unique","Reveals the Family members hit by a throwing knife only to Wyatt for 30 seconds.",[5,10]],
	[117,"blind spot","unique","Hitting Grandpa with a throwing knife makes Wyatt undetectable by him for his next scream. Also, the amount of Grandpa's blood is reduced by 50.",[2,10]],

	/*family perks*/
	[200,"activated","savagery","After being stunned, you deal 20% extra damage for 40 seconds.",[8,2]],
	[201,"battering ram","savagery","When barging a door, each consecutive hit is stronger by 100%.",[9,2]],
	[202,"big swings","savagery","Attack damage is increased by 15%, but stamina consumption tied to attacks is 200% more costly.",[0,3]],
	[203,"feral","savagery","Your Savagery is increased by 7.",[1,3]],
	[204,"hysterical strength","savagery","When below 20% stamina, you deal 20% more damage.",[2,3]],
	[205,"punishment","savagery","After finding a Victim in a hiding spot, 50 extra points of damage will be dealt.",[3,3]],
	[206,"rubber boots","savagery","You're immune to electrified cattle grids and the generator starts with only 1 pull.",[4,3]],
	[207,"serrated","savagery","Victims hit by the perk holder take 1HP per second of extra damage for the next 3.5 seconds.",[5,3]],
	[208,"tenderizer","savagery","Slamming a door on a Victim will deal 35 damage.",[6,3]],
	[209,"you'll pay for that!","savagery","If Grandpa is incapacitated, your damage dealt to Victims is increased by 25% until he recovers.",[7,3]],
	
	[210,"blood runner","blood-harvest","Speed is increased by 7% when carrying a full blood vial.",[1,0]],
	[211,"blood banker","blood-harvest","Your maximum blood storage capacity is increased by 50%.",[0,0]],
	[212,"dracula","blood-harvest","Winning a close encounter gives you 80% more blood, while losing a close encounter gives you 60 blood.",[2,0]],
	[213,"rage","blood-harvest","Successfully hitting a Victim will fill your ability bar by 25%.",[4,0]],
	[214,"siphon","blood-harvest","Your Blood Harvesting is increased by 7.",[5,0]],
	[215,"surgical","blood-harvest","You receive 100% more blood when attacking Victims.",[7,0]],
	[216,"universal donor","blood-harvest","Blood collected from buckets is increased by 50%.",[8,0]],
	[217,"vial-ent","blood-harvest","Your damage is increased by 20% when carrying a full blood vial.",[9,0]],
	[218,"warmed up","blood-harvest","After winning or losing a close encounter, you gain 100% to ability charge.",[0,1]],
	
	[219,"chicken whisperer","endurance","Chickens will not generate noise if you are spotted. Does not affect Victims.",[1,1]],
	[220,"confusing mechanic","endurance","After turning on a generator, it takes 30 seconds longer than usual for Victims to disable it.",[2,1]],
	[221,"dinner bell","endurance","Victims caught in traps will be highlighted, and your maximum stamina is increased by 60 points for 30 seconds.",[3,1]],
	[222,"down the rabbit hole","endurance","Victims who climb down wells will be highlighted for 25 seconds.",[4,1]],
	[223,"easily tuckered out","endurance","Your attacks use 30% less stamina, but your stamina regeneration rate is 15% slower.",[5,1]],
	[224,"fired up","endurance","After running out of stamina, there's a 75% less delay before stamina starts regenrating again.",[6,1]],
	[225,"hurt pride","endurance","After recovering from being stunned, your stamina recharges 80% faster for 30 seconds.",[7,1]],
	[226,"i smell blood","endurance","Your proximity range is increased by x5 to help you stay focused on the last Victim.",[8,1]],
	[227,"insulated","endurance","Booby-trapped lamps do not stun you.",[9,1]],
	[228,"pack animal","endurance","After being hit with a sneak attack, the attacking Victim is highlighted for 20 seconds.",[0,2]],
	[229,"scout","endurance","Your movement speed is increased by 5%, but stamina regeneration rate is 10% slower.",[1,2]],
	[230,"slow and steady","endurance","While sprinting, stamina usage is decreased by 50% but overall speed is reduced by 10%.",[2,2]],
	[231,"special blend","endurance","Walking through Sissy's poison clouds boosts your stamina regeneration by 50% for 60 seconds, and gives your next 1 attack a poison effect.",[3,2]],
	[232,"tracker tagged","endurance","Hitting a Victim highlights them for all Family members. Highlight duration is 8 seconds.",[5,2]],
	[233,"unrelenting","endurance","Your Endurance is increased by 7.",[6,2]],
	
	[234,"insult to injury","unique","Hitting a victim with your chainsaw reduces 20% of their stamina.",[8,3]],
	[239,"bloodlust","unique","Leatherface does 50% more damage after executing a Victim at the gallows.",[0,4]],
	/*PERK GONE [236,"bringing home the bacon","unique","Carrying a Victim highlights Leatherface to all Family members for 30 seconds.",[2,4]],*/
	[237,"efficient herbalist","unique","Poisoning an object has a 75% chance to not consume any powder.",[5,4]],
	[238,"linger","unique","Your toxic cloud lasts 15 seconds longer and is 3 meters larger in diameter.",[1,5]],
	[235,"quarter back","unique","Leatherface can knock Victims down with the chainsaw, even if it is turned off. Cooldown is 30 seconds.",[2,5]],
	[240,"patience","unique","Standing still will reduce your ability consumption rate by 100%.",[4,5]],
	[241,"prey drive","unique","Spotting a Victim increases stamina recharge by 60% for 20 seconds.",[7,5]],
	[242,"rough cut","unique","Hitting a Victim with the chainsaw causes 1.5HP of extra damage per second for 5 seconds.",[9,5]],
	[243,"rubber legs","unique","Your toxic cloud and poisoned items also slows Victims down by 20%.",[0,6]],
	[244,"security pins","unique","Added locks are 50% harder to unlock for Victims.",[1,6]],
	[245,"spore loser","unique","Losing a close encounter automatically drops an emergency poison cloud, even if you're out of powder. Cooldown is 30 seconds.",[4,6]],
	[246,"venom","unique","Victims caught in traps take 1HP of extra damage per second for 8 seconds.",[6,6]],
	[247,"wire frame","unique","You can traverse gaps 40% faster, and crawl spaces 60% faster.",[8,6]],

	[248,"sip sip sip","blood-harvest","Melee attacks give 300% more blood in your vial, but attack damage is reduced by 20%.",[6,0]],
	[249,"spring clean","endurance","Before Grandpa activates, your stamina consumption is reduced by 70%.",[4,2]],
	[250,"fresh is best","blood-harvest","Receive 100% more blood from landing hits on Victims, but 60% less blood from blood buckets.",[3,0]],
	[251,"wired","endurance","Victims climbing over obstacles are highlighted to you for 20 seconds.",[7,2]],
	[252,"barrier breaker","unique","The perk holder can break obstacles. Higher levels allow them to break the obstacle 30% quicker.",[9,3]],
	[253,"short fuse","unique","When a Victim is shocked by an electric trap, that Victim is highlighted to the perk holder for 15 seconds.",[2,6]],
	[254,"bruiser","unique","Victims hit by defensive barge take an additional 25 points of damage.",[3,4]],
	[255,"rip stalled","unique","After using the ripstall ability on an object, the object cannot be interacted with again by anyone for 45 more seconds.",[8,5]],
	[256,"blunt force trauma","unique","Attacks gain a concussive hit effect if above 100% stamina.",[1,4]],
	[257,"slow hands","unique","Victims that trigger an electric trap complete hold and tap interactions 40% slower for 60 seconds.",[3,6]],
	[258,"ding dong","unique","The bell attached to strands of barbed wire will ring 150% louder, and its highlight range will be increased by 70%.",[4,4]],
	[259,"give me more","unique","Nancy's ability regeneration rate is increased by 20% but stamina regeneration is reduced by 10%.",[6,4]],
	[260,"hey sissy","unique","Ingesting Sissy's powder reduces ability cooldown rate by 20%, but causes 15 seconds of blurry vision the next time your ability is used.",[8,4]],
	[261,"hurt 'em","unique","Barbed wire traps do 15 damage. Increases damage dealt to a Victim caught in barbed wire if they continue to run while the barbed wire is attached to them.",[9,4]],
	[262,"i'll kill them all","unique","After using her ability, Nancy's damage is increased by 15% for 60 seconds.",[0,5]],
	[263,"not that easy","unique","Barbed wire is 70% harder for Victims to remove.",[3,5]],
	[264,"pins and needles","unique","Placing a strand of barbed wire has a 33% chance to not consume an inventory item.",[5,5]],
	[265,"poisoned claws","unique","Melee attacks apply a slight poison effect for 8 seconds.",[6,5]],
	[266,"strong minded","unique","After using her ability, Nancy's stamina depletion is reduced by 30% for 45 seconds.",[5,6]],
	[267,"wait a second","unique","Victims who get tangled in barbed wire must wait 15 seconds before removing it.",[7,6]],
	[268,"heart attack","unique","A Victim's bleed out is increased by 180 seconds if they trigger an electric trap or are hit by barge.",[7,4]],
	[269,"hunting enthusiast","unique","Bones can traverse barricades. His speed to crawl over obstacles is increased by 120%.",[9,6]],
	[270,"reckless","unique","Bones can jump through windows. He needs 2 seconds to recover.",[1,7]],
	[271,"muscle memory","unique","Gore bomb crafting and modifying durations are 90% shorter.",[3,7]],
	[272,"resourceful engineer","unique","Bones can create a gore bomb directly on the site of a detonated bomb. Consumes 40% of the blood remaining in his blood vial. This cannot be used if the blood vial is empty.",[2,7]],
	[273,"no escape","unique","Bones can jump down wells. He needs 3 seconds to recover. Bones cannot jump down wells until Grandpa wakes up.",[0,7]],
	
	/*character abilities*/
	[400,"focused","ability","Using Focused allows a door to be unlocked almost instantly, but stamina and Family proximity warning are negatively impacted.",[0,0]],
	[401,"life saver","ability","Defend yourself or teammates by knocking down and stunning Family members.",[1,0]],
	[402,"pain is nothing","ability","While active, significantly reduces damage taken from attacks and falls, while also granting immunity to the effects of poison.",[2,0]],
	[403,"heightened sense","ability","Detect noise made by anyone nearby, pinpointing their location and tracking their movements.",[3,0]],
	[404,"ultimate escape","ability","While active, grants immunity to tracking from The Cook and Johnny while greatly reducing stamina consumption while sprinting.",[4,0]],
	[405,"study and tamper","ability","Build knowledge by studying objects, and use that knowledge to tamper with exit interactions. Tampered exits stay open or shutdown longer.",[0,1]],
	[406,"boon","ability","Throw powder found around the properties to blind Family members or contaminate blood buckets.",[1,1]],
	[407,"sweet talk","ability","Causes Grandpa's Sonar ability to highlight Family members instead of Victims.",[2,1]],
	[408,"knife throw","ability","Wyatt can throw knives at Family members in order to stun them.",[0,3]],
	
	[420,"maim","ability","Use the chainsaw to cause horrific injuries, and destroy any doors or obstacles that might stand in your way.",[3,1]],
	[421,"seek","ability","Listen for noisy Victims, highlighting and pinpointing their location for a short period of time.",[4,1]],
	[422,"trap","ability","Set traps on the ground, snaring, and injuring any Victims who step on them.",[0,2]],
	[423,"hunt","ability","Track the movement of Victims while searching for any footprints left behind.",[1,2]],
	[424,"bane","ability","Blow clouds of poison in the path of Victims to block their paths, or lace their useful items.",[2,2]],
	[425,"ripstall","ability","Lock down exit interactions by ripping fuses out of the fusebox, valve handles from the tank and restarting the Generator and Car Battery quickly.",[3,2]],
	[426,"spy","ability","See through the eyes of one of the Victims, revealing an approximate location.",[4,2]],
	[427,"gore bomb","ability","Plant a homemade gore bomb to severely injure unsuspecting Victims and blow up nearby doors & obstacles. Victims hit by a gore bomb are revealed to Bones for 15 seconds.",[1,3]],

	/*grandpa abilities*/
	[600,"always in sync","grandpa","When active, the Family Focus ability duration is increased and the cooldown is reduced.",[0,0]],
	[601,"animal farm",'grandpa',"Increases chicken detection radius.",[1,0]],
	[602,"barge to the point",'grandpa',"Barging doors always opens them on the first try.",[2,0]],
	[603,"brute strength",'grandpa',"Slightly increases melee damage for all Family members.",[3,0]],
	[604,"don't have all day",'grandpa',"Stamina drain while sprinting is decreased by 25%.",[4,0]],
	[605,"excited grandpa",'grandpa',"Delay between Grandpa's Sonar ability is reduced by 25% at each level.",[0,1]],
	[606,"experienced stalkers",'grandpa',"Reduces the Family's proximity warning range for Victims.",[1,1]],
	[607,"exterior alarms",'grandpa',"When active, all critical doors and gates are highlighted for 10 seconds if opened.",[2,1]],
	[608,"nobody escapes hell",'grandpa',"Door unlock minigames are 50% harder for all Victims.",[3,1]],
	[609,"suffocating grip",'grandpa',"Close encounter minigame is easier by 25% for the perk holder.",[4,1]],
	[610,"swinging for the fences",'grandpa',"Reduces stamina consumption on melee atacks by 25%.",[0,2]],
	[611,"well fed young'uns",'grandpa',"Whenever Grandpa's Sonar is activated, all Family members instantly regain 50 stamina.",[1,2]],
	[612,"well well well",'grandpa',"Victims that jump down wells take 50% more damage.",[2,2]],
	[613,"windoom",'grandpa',"Victims take 50% more damage when jumping out of windows.",[3,2]]
];
